#!/usr/bin/env python3
"""
Protobuf message definitions for stock pipeline events
Generated from events.proto

To regenerate these bindings:
  protoc --python_out=. events.proto
"""

# This is a stub that will be auto-generated by protoc
# For now, we provide a basic implementation that can be generated with:
# python3 -m grpc_tools.protoc -I. --python_out=. events.proto

import sys
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import descriptor_pool as _descriptor_pool

_sym_db = _descriptor.SymbolDatabase()

DESCRIPTOR = _descriptor_pool.Default()

# Message definitions
class FinancialData(_message.Message):
    """Financial data record"""
    pass

class StockMovement(_message.Message):
    """Stock movement data"""
    pass

class NewsData(_message.Message):
    """News data record"""
    pass

class MacroeconomicData(_message.Message):
    """Macroeconomic data"""
    pass

class PolicyData(_message.Message):
    """Policy data record"""
    pass

class DataBatch(_message.Message):
    """Batch container for multiple records"""
    pass

class Event(_message.Message):
    """Generic event wrapper"""
    pass

# Register message types
__all__ = [
    'FinancialData',
    'StockMovement',
    'NewsData',
    'MacroeconomicData',
    'PolicyData',
    'DataBatch',
    'Event',
]
